
package com.realdolmen.payment.jaxb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentPortService", targetNamespace = "http://realdolmen.com/payment/JAXB", wsdlLocation = "http://thomasmorejenkins.ddns.net:8090/ws/payment.wsdl")
public class PaymentPortService
    extends Service
{

    private final static URL PAYMENTPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTPORTSERVICE_EXCEPTION;
    private final static QName PAYMENTPORTSERVICE_QNAME = new QName("http://realdolmen.com/payment/JAXB", "PaymentPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://thomasmorejenkins.ddns.net:8090/ws/payment.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTPORTSERVICE_WSDL_LOCATION = url;
        PAYMENTPORTSERVICE_EXCEPTION = e;
    }

    public PaymentPortService() {
        super(__getWsdlLocation(), PAYMENTPORTSERVICE_QNAME);
    }

    public PaymentPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTPORTSERVICE_QNAME, features);
    }

    public PaymentPortService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTPORTSERVICE_QNAME);
    }

    public PaymentPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTPORTSERVICE_QNAME, features);
    }

    public PaymentPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentPort
     */
    @WebEndpoint(name = "PaymentPortSoap11")
    public PaymentPort getPaymentPortSoap11() {
        return super.getPort(new QName("http://realdolmen.com/payment/JAXB", "PaymentPortSoap11"), PaymentPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPort
     */
    @WebEndpoint(name = "PaymentPortSoap11")
    public PaymentPort getPaymentPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://realdolmen.com/payment/JAXB", "PaymentPortSoap11"), PaymentPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTPORTSERVICE_EXCEPTION!= null) {
            throw PAYMENTPORTSERVICE_EXCEPTION;
        }
        return PAYMENTPORTSERVICE_WSDL_LOCATION;
    }

}
